config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_forms do
    scope module: :user_forms do
      resource :user_form_messages, only: [:new, :create]
    end
  end
  root to: 'user_forms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  has_many :user_form_messages, inverse_of: :user_form, dependent: :destroy
  validates :name, length: { minimum: 2, maximum: 60 }
end

app/models/user_form_message.rb
class UserFormMessage < ApplicationRecord
  belongs_to :user_form, inverse_of: :user_form_messages
  validates :name, :email, :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(user)
    return new_user_form_path if UserForm.count == 0
    super
  end

  def after_sign_out_path_for(user)
    new_user_session_path
  end
end

app/controllers/confirmations_controller.rb
# frozen_string_literal: true

class ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
end

app/controllers/unlocks_controller.rb
# frozen_string_literal: true

class UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_forms/user_form_messages_controller.rb
class UserForms::UserFormMessagesController < ApplicationController
  before_action :authenticate_user!

  layout "user_forms"

  def new
    @user_form = UserForm.find(params[:user_form_id])
    @user_form_message = UserFormMessage.new({user_form_id: @user_form.id})
  end

  def create
    @user_form = UserForm.find(params[:user_form_id])
    @user_form_message = UserFormMessage.new({user_form_id: @user_form.id}.merge(user_form_message_params))
    if @user_form_message.save
      flash.notice = t('.success')
      redirect_to user_form_path(params[:user_form_id])
    else
      flash.notice = @user_form_message.errors.full_messages
      render :new
    end
  end

  private

  def user_form_message_params
    params.require(:user_form_message).permit(:name, :email, :message)
  end
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  before_action :authenticate_user!

	def index
    @user_forms = UserForm.all
  end

  def new
  	@user_form = UserForm.new
  end

  def create
  	@user_form = UserForm.new(user_form_params)
  	if @user_form.save
  		flash.notice = t('.success')
  		redirect_to new_user_form_user_form_messages_path(user_form_id: @user_form.id)
  	else
      render :new
  	end
  end

  def show
    @user_form = UserForm.find(params[:id])
    @user_form_messages = @user_form.user_form_messages
  end

  def destroy
    @user_form = UserForm.find(params[:id])
    if @user_form.destroy
      flash.notice = t('.success', name: @user_form.name)
    end
    redirect_to user_forms_path
  end

  private

  def user_form_params
  	params.require(:user_form).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/user_forms_helper.rb
module UserFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.typekit.net/zhh0qyl.css">
    <link href="//cdn.muicss.com/mui-0.10.2/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.10.2/js/mui.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'partials/header' %></header>
    <section class= 'formapp__container'>
      <%= yield %>
    </section>
    <footer><%= render 'partials/footer' %></footer>
  </body>
</html>

app/views/layouts/user_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.typekit.net/zhh0qyl.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'users/partials/header' %>
    </header>
    <section class= 'formapp__container'>

      <%= render 'partials/flash' %>
      <%= yield %>
    </section>
    <footer><%= render 'partials/footer' %></footer>
  </body>
</html>

app/views/layouts/user_forms.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.typekit.net/zhh0qyl.css">
    <link href="//cdn.muicss.com/mui-0.10.2/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.10.2/js/mui.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'users/partials/header' %>
    </header>
    <section class= 'formapp__container'>

      <%= render 'users/partials/flash' %>
      <%= yield %>
    </section>
    <footer><%= render 'partials/footer' %></footer>
  </body>
</html>

app/views/partials/_flash.erb
<% if flash[:notice] %>
  <article class='flash__notice'>
    <%= inline_svg_tag 'success.svg', class: 'flash__notice--icon' %>
    <%= flash[:notice] %>
  </article>
<% end %>

<% [ flash[:alert] ].flatten.compact.each do |alert| %>
  <article class="flash__alert">
    <%= inline_svg_tag 'error.svg', class: 'flash__alert--icon' %>
    <%= alert %>
  </article>
<% end %>

app/views/partials/_footer.erb
<section class='formapp-footer'>
  <section class='formapp-footer__container'>
    <section class='formapp-footer__content'>
      <article class='formapp-footer__content--lower'><%= link_to t(:copyright, scope: [:footer]) + " " + Date.current.year.to_s +  " " + t(:ministry_of_velocity, scope: [:footer]), 'http://www.ministryofvelocity.com', class: 'formapp-footer__content--links' %></article>
    </section>
  </section>
</section>

app/views/partials/_header.erb
<section class= 'formapp-header'>
  <section class= 'formapp-header__container'>
    <p class= 'formapp-header__title'>
      <%= link_to 'FormApp', root_path, class: 'formapp-header__link', title: t(:title, scope: :header) %>
    </p>
  </section>
</section>

app/views/partials/_header.html.erb
<section><%= link_to "FormApp", root_path %></section>
<section>
  <%= link_to "Create New Form", root_path %>
  <%= link_to "My Forms", root_path %>
  <%= link_to "Forms Settings", root_path %>
  <%= link_to "Account", root_path %>
  <%= link_to "Sign Out", root_path %>
</section>

app/views/user_form/new.html.erb
<h1>Create a User Form</h1>
<p>Here is where your form journey begins!</p>
<br>
<p>Enter your new form name here:</p>
<%= form_for @user_form do |f| -%>
	Form Name: <%= f.text_field :formname %> <br />
	<%= f.submit %>
<% end -%>

<hr>

<p>Display all created forms</p> <br>
<% if !@user_forms.blank? %>
	<% for item in @user_forms %>
		<%= item.formname %> <br />
	<% end %>
<% else %>

<% end %>

app/views/user_forms/index.html.erb
<section class= 'my_forms__title'> <%= t('.title') %></section>
<section class= 'my_forms__content'>
  <article class='my_forms__link'><%= link_to t('.add_new_form'), new_user_form_path %></article>

  <% @user_forms.each do |user_form| %>
    <article class= 'my_forms__list'>
      <article class= 'my_forms__link'><%= link_to user_form.name, user_form_path(id: user_form.id) %></article>
    </article>
  <% end %>
</section>

app/views/user_forms/new.html.erb
<section class= 'create-form__title'> <%= t('.title') %></section>
<section class= 'user-flash__alert'>
 <% @user_form.errors.full_messages.each do |error| %>
  <%= inline_svg_tag 'error.svg', class: 'user-flash__alert--icon' %>
  <%= t('.error') %>
  <%= error %>
 <% end %>
</section>
<section class= 'create-form__form--content'>
  <%= form_for @user_form do |f| -%>
    <%= f.label :name, t('.name') %>
    <%= f.text_field :name, :class => 'create-form__form--text-field', :maxlength =>'60' %>
    <%= f.submit t('.submit'), :class => 'mui-btn mui-btn--danger sign-up__form--button' %>
  <% end -%>
</section>

app/views/user_forms/show.html.erb
<section class= 'form_inbox__title'> <%= t('.title') %></section>
<section class= 'form_inbox__content'>
  <%= @user_form.name %>
  <article class= 'my_forms__link'><%= link_to t('.delete_form'), user_form_path(id: @user_form.id), method:'delete', data: { confirm: t('.delete_confirmation_message') }%></article>
  <%= link_to "Back to Preview", new_user_form_user_form_messages_path(user_form_id: @user_form.id) %>
  <%= @user_form_messages.inspect %>
</section>

app/views/user_forms/user_form_messages/new.html.erb
<section class= 'user-form-message__title'> <%= t('.title') %></section>
<%= form_for @user_form_message, url: user_form_user_form_messages_path(@user_form.id) do |f| -%>
  <%= f.label :name, t('.name') %>
  <%= f.text_field :name, :class => 'user-form-message__form--text-field', :maxlength =>'60' %>
  <%= f.label :email, t('.email') %>
  <%= f.text_field :email, :class => 'user-form-message__form--text-field', :maxlength =>'60' %>
  <%= f.label :message, t('.message') %>
  <%= f.text_field :message, :class => 'user-form-message__form--text-field', :maxlength =>'60' %>
  <%= f.submit t('.submit'), :class => 'mui-btn mui-btn--danger user-form-message__form--button' %>
<% end -%>

app/views/users/partials/_flash.erb
<% if flash[:notice] %>
  <section class='user-flash__container'>
    <article class='user-flash__notice'>
      <%= inline_svg_tag 'success.svg', class: 'user-flash__notice--icon' %>
      <%= flash[:notice] %>
    </article>
  </section>
<% end %>

<% [ flash[:alert] ].flatten.compact.each do |alert| %>
  <article class="user-flash__alert">
    <%= inline_svg_tag 'error.svg', class: 'user-flash__alert--icon' %>
    <%= alert %>
  </article>
<% end %>

app/views/users/partials/_header.erb
<section class= 'formapp-header'>
  <section class= 'formapp-header__container'>
    <p class= 'formapp-header__title'>
      <%= link_to 'FormApp', root_path, class: 'formapp-header__link', title: t(:title, scope: :header) %>
    </p>

    <input type='checkbox' id='formapp-header__navigation-toggle-input' class='formapp-header__navigation-toggle-input' aria-label='<%= t(:toggle_menu, scope: [:header]) %>' />
    <label class='formapp-header__navigation-toggle' for='formapp-header__navigation-toggle-input'>
      <span class='formapp-header__navigation-toggle-bar formapp-header__navigation-toggle-bar--top'></span>
      <span class='formapp-header__navigation-toggle-bar formapp-header__navigation-toggle-bar--bottom'></span>
    </label>

    <nav class= 'formapp-header__navigation'>
      <%= link_to t(:create_new_form, scope: [:header]), new_user_form_path, class: 'formapp-header__link' %>
      <%= link_to t(:my_forms, scope: [:header]), user_forms_path, class: 'formapp-header__link' %>
      <%= link_to t(:sign_out, scope: [:header]), destroy_user_session_path, method: :delete, class: 'formapp-header__link' %>
    </nav>
  </section>
</section>